"""Regenerate ``blender_gala/pymol/palette.py`` from a real PyMOL.

A session stores colours as *indices* into PyMOL's built-in table, so reading
one without PyMOL means carrying that table. It is compiled into PyMOL rather
than published as data, so this script asks a real PyMOL for it:

    /Applications/PyMOL.app/Contents/MacOS/PyMOL -cq scripts/make_pymol_palette.py

or with ``pymol`` on PATH::

    pymol -cq scripts/make_pymol_palette.py

Run it only when supporting a newer PyMOL whose table has grown; the generated
module is committed, and Gala never needs PyMOL at run time.
"""

from __future__ import annotations

import os
import textwrap

from pymol import cmd  # type: ignore[import-not-found]


def _repo_root() -> str:
    """Find the checkout, without trusting ``__file__``.

    PyMOL execs a ``-cq`` script in a namespace whose ``__file__`` points into
    its own site-packages, so deriving the repository from it writes the
    generated module inside PyMOL.app. Walking up from the working directory
    for the manifest is unambiguous.
    """
    for start in (os.environ.get("GALA_ROOT"), os.getcwd()):
        if not start:
            continue
        current = os.path.abspath(start)
        while True:
            if os.path.exists(
                os.path.join(current, "blender_gala", "blender_manifest.toml")
            ):
                return current
            parent = os.path.dirname(current)
            if parent == current:
                break
            current = parent
    raise SystemExit("run this from the blender_gala checkout, or set GALA_ROOT to it")


TARGET = os.path.join(_repo_root(), "blender_gala", "pymol", "palette.py")

HEADER = '''\
"""PyMOL's built-in colour table.

A ``.pse`` stores every atom's colour as an index into the table PyMOL
compiles in, so reading one faithfully means carrying that table. This module
is generated by ``scripts/make_pymol_palette.py`` from PyMOL {version}, where
the table has {count} entries with indices {low}-{high}.

Colours are stored as 8-bit hex, which is how all but the computed greys were
defined in the first place; the round trip is within 1/255 of what PyMOL
reports. Named lookups are case-insensitive, matching ``cmd.color``.
"""

from __future__ import annotations

__all__ = [
    "COUNT",
    "PYMOL_VERSION",
    "SPECIAL",
    "index_for_name",
    "name_for_index",
    "rgb_for_index",
]

#: The PyMOL these were read from.
PYMOL_VERSION = "{version}"

#: How many built-in colours there are; indices run ``0..COUNT - 1``.
COUNT = {count}

#: Indices with a meaning rather than a colour. ``atomic`` means "colour by
#: element", which is resolved per atom rather than from this table.
SPECIAL = {special}

# Six hex digits per colour, in index order.
_HEX = (
'''

FOOTER = '''

#: Names in index order, space separated.
_NAMES = (
{names}
)

_names: list[str] | None = None
_by_name: dict[str, int] | None = None


def _table() -> tuple[list[str], dict[str, int]]:
    """Split the name blob once, on first use."""
    global _names, _by_name
    if _names is None or _by_name is None:
        _names = _NAMES.split()
        _by_name = {{name: index for index, name in enumerate(_names)}}
    return _names, _by_name


def rgb_for_index(index: int) -> tuple[float, float, float] | None:
    """Return the ``(r, g, b)`` for a built-in colour index, or ``None``.

    Parameters
    ----------
    index : int
        A PyMOL colour index. Session-local colours (``>= COUNT``) and the
        negative :data:`SPECIAL` values are not in this table and return
        ``None``, which is the caller's cue to resolve them itself.

    Returns
    -------
    tuple of float or None
        Channels in 0-1.
    """
    if index < 0 or index >= COUNT:
        return None
    start = index * 6
    chunk = _HEX[start : start + 6]
    return (
        int(chunk[0:2], 16) / 255.0,
        int(chunk[2:4], 16) / 255.0,
        int(chunk[4:6], 16) / 255.0,
    )


def name_for_index(index: int) -> str | None:
    """Return the name of a built-in colour index, or ``None``."""
    if index in SPECIAL:
        return SPECIAL[index]
    if index < 0 or index >= COUNT:
        return None
    return _table()[0][index]


def index_for_name(name: str) -> int | None:
    """Return the index of a named built-in colour, or ``None``.

    Case-insensitive, as ``cmd.color`` is.
    """
    return _table()[1].get(name.strip().lower())
'''


def main() -> None:
    version = cmd.get_version()[0]
    entries = cmd.get_color_indices(all=1)
    by_index = {index: name for name, index in entries}

    low, high = min(by_index), max(by_index)
    missing = [i for i in range(low, high + 1) if i not in by_index]
    if low != 0 or missing:
        raise SystemExit(
            f"expected a dense table from 0; got {low}-{high} with "
            f"{len(missing)} gaps. The generator assumes index == position."
        )

    hex_digits = []
    names = []
    for index in range(high + 1):
        red, green, blue = cmd.get_color_tuple(index)
        hex_digits.append(
            "".join(
                f"{max(0, min(255, round(c * 255))):02x}" for c in (red, green, blue)
            )
        )
        names.append(by_index[index])

    special = {
        cmd.get_color_index(name): name
        for name in ("default", "atomic", "front", "back")
        if cmd.get_color_index(name) < 0
    }

    body = HEADER.format(
        version=version,
        count=high + 1,
        low=low,
        high=high,
        special=repr(dict(sorted(special.items()))),
    )
    body += _wrap("".join(hex_digits))
    body += "\n)\n"
    body += FOOTER.format(names=_wrap(" ".join(names), quote_space=True))

    os.makedirs(os.path.dirname(TARGET), exist_ok=True)
    with open(TARGET, "w") as handle:
        handle.write(body)
    print(f"wrote {TARGET}: {high + 1} colours from PyMOL {version}")


def _wrap(text: str, quote_space: bool = False) -> str:
    """Break a long string into quoted, indented, concatenated chunks."""
    width = 72
    if quote_space:
        # Break on spaces so no colour name is split across two literals.
        lines = textwrap.wrap(text, width=width, break_long_words=False)
        # Each chunk keeps a trailing space so the concatenated literal still
        # has a separator where the wrap fell.
        return "\n".join(f'    "{line} "' for line in lines)
    chunks = [text[i : i + width] for i in range(0, len(text), width)]
    return "\n".join(f'    "{chunk}"' for chunk in chunks)


# Not guarded by ``__name__ == "__main__"``: PyMOL execs a ``-cq`` script in a
# namespace of its own, where that guard is never true and the script would
# silently do nothing.
main()
