"""Generate ``CITATION.cff`` from the extension manifest.

GitHub reads ``CITATION.cff`` and turns it into the *Cite this repository*
button, which means the version in it is one more place the release number can
go stale — and a citation that names the wrong version is worse than no
citation, because it looks authoritative.

So it is generated rather than written. ``blender_manifest.toml`` is where the
version lives (Blender requires a literal there, and everything else in the
repository reads it from there); the release date comes from the ``v<version>``
tag, which is the only record of when that version actually shipped.

    python scripts/make_citation.py            # write CITATION.cff
    python scripts/make_citation.py --check    # fail if it is out of date

The check runs in CI, so a version bump that forgets this file cannot merge.
It deliberately ignores ``date-released``, which is the one field that cannot
be right at the moment it is written: the date comes from the ``v<version>``
tag, and the commit that bumps the version is necessarily made before that tag
exists. Comparing it would leave the repository red between the bump and the
tag, for a field nobody bumped.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tomllib

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(HERE, "blender_gala", "blender_manifest.toml")
PYPROJECT = os.path.join(HERE, "pyproject.toml")
OUT_PATH = os.path.join(HERE, "CITATION.cff")

REPOSITORY = "https://github.com/maomlab/blender_gala"


def read(path: str) -> dict:
    with open(path, "rb") as handle:
        return tomllib.load(handle)


def split_maintainer(maintainer: str) -> tuple[str, str, str]:
    """Split ``"Matthew O'Meara <maom@umich.edu>"`` into its three parts.

    CFF wants given and family names separately. The manifest stores one
    string, because that is what Blender asks for.
    """
    name, _, email = maintainer.partition("<")
    given, _, family = name.strip().rpartition(" ")
    return given, family, email.strip(" >")


def released(version: str) -> str | None:
    """The date the ``v<version>`` tag was made, or ``None`` if it was not.

    A version that has not been tagged has not been released, and guessing a
    date for it — today's, say — would put a fact in the file that nobody
    checked.
    """
    try:
        stamp = subprocess.run(
            ["git", "log", "-1", "--format=%ad", "--date=short", f"v{version}"],
            cwd=HERE,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, OSError):
        return None
    return stamp or None


def quote(value: str) -> str:
    """Double-quote a scalar. The maintainer's name has an apostrophe in it."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render() -> str:
    manifest = read(MANIFEST)
    version = manifest["version"]
    given, family, email = split_maintainer(manifest["maintainer"])
    # The manifest writes licences as SPDX identifiers with the prefix Blender
    # wants; CFF wants the identifier on its own.
    licence = manifest["license"][0].removeprefix("SPDX:")

    lines = [
        "# Generated by scripts/make_citation.py — do not edit.",
        "#",
        "# The version and the licence come from blender_gala/blender_manifest.toml,",
        "# the release date from the matching git tag, and the keywords from",
        "# pyproject.toml. Run `make citation` after a version bump.",
        "cff-version: 1.2.0",
        "message: " + quote("If you use this software, please cite it as below."),
        "title: " + quote(manifest["name"]),
        "abstract: " + quote(manifest["tagline"]),
        "type: software",
        "version: " + quote(str(version)),
    ]

    date = released(str(version))
    if date:
        lines.append("date-released: " + quote(date))

    lines += [
        "license: " + quote(licence),
        "repository-code: " + quote(REPOSITORY),
        "url: " + quote(manifest["website"]),
        "authors:",
        "  - family-names: " + quote(family),
        "    given-names: " + quote(given),
        "    email: " + quote(email),
    ]

    keywords = read(PYPROJECT)["project"].get("keywords", [])
    if keywords:
        lines.append("keywords:")
        lines += ["  - " + quote(word) for word in keywords]

    return "\n".join(lines) + "\n"


def _without_date(text: str) -> str:
    """The file with its release date removed. See the module docstring."""
    return "\n".join(
        line for line in text.splitlines() if not line.startswith("date-released:")
    )


def main(argv: list[str]) -> None:
    wanted = render()
    if "--check" in argv:
        try:
            with open(OUT_PATH, encoding="utf-8") as handle:
                current = handle.read()
        except FileNotFoundError:
            raise SystemExit("CITATION.cff is missing. Run: make citation") from None
        if _without_date(current) != _without_date(wanted):
            raise SystemExit(
                "CITATION.cff is out of date with blender_manifest.toml. "
                "Run: make citation"
            )
        print(f"  CITATION.cff matches the manifest ({OUT_PATH})")
        return

    with open(OUT_PATH, "w", encoding="utf-8") as handle:
        handle.write(wanted)
    print(f"  wrote {OUT_PATH}")


if __name__ == "__main__":
    main(sys.argv[1:])
