"""Generate the test structures under ``tests/data``.

The fixtures are synthetic and built from exact coordinates so that tests can
assert real numbers — a 2.80 A hydrogen bond is 2.80 A because it was placed
there, not because a real structure happened to have one. Run with any Python
that has no dependencies beyond the standard library::

    python tests/data/make_fixtures.py

Committed output:

``site.pdb``
    A synthetic binding site exercising every interaction detector: a hydrogen
    bond with an explicit hydrogen, a salt bridge, an aromatic stack, a
    cation-pi, a halogen bond, a metal centre, a hydrophobic pair, plus a
    water and a monoatomic ion.
``plddt.pdb``
    A poly-alanine chain whose B-factors sweep the four AlphaFold confidence
    bands.
``geometry.pdb``
    Four atoms at coordinates with an exactly known distance, angle and
    dihedral.
``awkward.pdb`` / ``awkward.cif``
    The same structure in both formats, carrying the complications real
    depositions carry: alternate locations, insertion codes, an expression tag
    numbered below one, a gap in the numbering, selenomethionine, an
    unidentified residue, a lower-case chain beside an upper-case one, a
    calcium named like a C-alpha, a zero-occupancy atom, a missing element
    column, formal charges and a duplicated atom. The mmCIF version keeps its
    ``label_*`` identifiers deliberately apart from its ``auth_*`` ones.
``nucleic.pdb``
    A DNA dinucleotide and an RNA one, for the half of the selection language
    that nothing else here reaches.
``ensemble.pdb``
    The pLDDT chain as three models, the way an NMR deposition is written.
"""

from __future__ import annotations

import math
import os
from typing import NamedTuple

HEADER = "REMARK   Synthetic fixture generated by tests/data/make_fixtures.py\n"

#: Residue names written as HETATM rather than ATOM.
HETERO_RESIDUES = ("LIG", "HOH", "ZN", "CL", "NAG", "UNL", "SO4")


class Atom(NamedTuple):
    """One atom, in the fields a PDB ATOM record has columns for.

    The trailing five are the ones only the awkward fixtures use; a structure
    that needs none of them reads exactly as it did before they existed.
    """

    serial: int
    name: str
    res_name: str
    chain: str
    res_id: int
    x: float
    y: float
    z: float
    occupancy: float = 1.0
    b_factor: float = 0.0
    element: str = ""
    altloc: str = ""
    ins_code: str = ""
    charge: str = ""
    hetero: bool | None = None


def line(atom: Atom) -> str:
    """Render one ATOM/HETATM record, by column.

    The columns are placed explicitly rather than by counting spaces, because
    the alternate-location and insertion-code fields sit *inside* what would
    otherwise be padding — column 17 between the atom name and the residue
    name, and column 27 between the residue number and the coordinates. A
    reader that takes them by position, which every PDB reader does, sees a
    different structure if either is off by one.
    """
    hetero = atom.hetero
    if hetero is None:
        hetero = atom.res_name in HETERO_RESIDUES
    record = "HETATM" if hetero else "ATOM  "
    # A name of four characters starts in column 13; a shorter one is indented
    # by one, which is what puts the element symbol in 13-14 where it belongs.
    padded = atom.name if len(atom.name) >= 4 else f" {atom.name:<3}"
    return (
        f"{record}{atom.serial:5d} {padded}{atom.altloc:1}{atom.res_name:>3} "
        f"{atom.chain:1}{atom.res_id:4d}{atom.ins_code:1}   "
        f"{atom.x:8.3f}{atom.y:8.3f}{atom.z:8.3f}"
        f"{atom.occupancy:6.2f}{atom.b_factor:6.2f}"
        f"{'':10}{atom.element:>2}{atom.charge:>2}"
    ).rstrip() + "\n"


def write(path: str, atoms: list[Atom], models: int = 1) -> None:
    """Write a PDB file, optionally as several models of the same atoms.

    ``models`` greater than one wraps each copy in MODEL/ENDMDL and rotates the
    coordinates a little between them, which is what an NMR ensemble looks
    like to a reader.
    """
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(HEADER)
        for model in range(models):
            if models > 1:
                handle.write(f"MODEL     {model + 1:4d}\n")
            for atom in atoms:
                handle.write(line(_displaced(atom, model)))
            if models > 1:
                handle.write("ENDMDL\n")
        handle.write("END\n")
    count = f"{len(atoms)} atoms" + (f" x {models} models" if models > 1 else "")
    print(f"wrote {path} ({count})")


def _displaced(atom: Atom, model: int) -> Atom:
    """Nudge an atom by a fixed amount per model. Model 0 is untouched."""
    if not model:
        return atom
    shift = 0.25 * model
    return atom._replace(x=atom.x + shift, y=atom.y - shift, z=atom.z + shift)


def ring(centre, normal_axis: str, radius: float = 1.39, start: float = 0.0):
    """Regular hexagon of ring atoms in a plane normal to ``normal_axis``."""
    cx, cy, cz = centre
    points = []
    for i in range(6):
        angle = start + i * math.pi / 3.0
        dx, dy = radius * math.cos(angle), radius * math.sin(angle)
        if normal_axis == "z":
            points.append((cx + dx, cy + dy, cz))
        elif normal_axis == "y":
            points.append((cx + dx, cy, cz + dy))
        else:
            points.append((cx, cy + dx, cz + dy))
    return points


def site() -> list[Atom]:
    atoms: list[Atom] = []
    serial = 1

    def add(name, res_name, chain, res_id, xyz, b=30.0, element=None, occupancy=1.0):
        nonlocal serial
        element = element or name[0]
        atoms.append(
            Atom(
                serial,
                name,
                res_name,
                chain,
                res_id,
                xyz[0],
                xyz[1],
                xyz[2],
                occupancy,
                b,
                element,
            )
        )
        serial += 1

    # --- SER 1: donates a hydrogen bond to ASP 2 OD1 -----------------------
    # OG at (0,0,0); HG points at OD1 so the D-H...A angle is exactly 180.
    add("N", "SER", "A", 1, (-2.5, 1.2, 0.0))
    add("CA", "SER", "A", 1, (-1.5, 0.2, 0.0))
    add("C", "SER", "A", 1, (-2.0, -1.2, 0.0))
    add("O", "SER", "A", 1, (-3.2, -1.5, 0.0))
    add("CB", "SER", "A", 1, (-0.7, 0.5, 1.2))
    add("OG", "SER", "A", 1, (0.0, 0.0, 0.0))
    add("HG", "SER", "A", 1, (0.98, 0.0, 0.0), element="H")

    # --- ASP 2: acceptor at exactly 2.80 A from SER OG --------------------
    add("N", "ASP", "A", 2, (5.0, 3.0, 0.0))
    add("CA", "ASP", "A", 2, (4.5, 1.8, 0.0))
    add("C", "ASP", "A", 2, (5.5, 0.8, 0.6))
    add("O", "ASP", "A", 2, (6.6, 1.2, 1.0))
    add("CB", "ASP", "A", 2, (4.0, -0.3, -0.9))
    add("CG", "ASP", "A", 2, (3.5, -0.6, 0.4))
    add("OD1", "ASP", "A", 2, (2.80, 0.0, 0.0))
    add("OD2", "ASP", "A", 2, (3.9, -1.6, 1.0))

    # --- LYS 3: salt bridge to ASP 2, and cation-pi over the ligand ring ---
    add("N", "LYS", "A", 3, (7.0, -3.0, 0.0))
    add("CA", "LYS", "A", 3, (6.5, -2.0, 0.9))
    add("C", "LYS", "A", 3, (7.5, -1.0, 1.4))
    add("O", "LYS", "A", 3, (8.6, -1.3, 1.8))
    add("CB", "LYS", "A", 3, (5.5, -1.3, 0.1))
    add("CG", "LYS", "A", 3, (4.8, -2.2, -0.9))
    add("CD", "LYS", "A", 3, (4.0, -3.2, -0.2))
    add("CE", "LYS", "A", 3, (3.4, -4.0, -1.3))
    # NZ 4.30 A from the carboxylate centroid (2.90, -0.80, 0.50): a salt bridge.
    add("NZ", "LYS", "A", 3, (2.90, -5.10, 0.50))

    # --- PHE 4: aromatic ring in the z = 0 plane, centred at (0, 8, 0) -----
    add("N", "PHE", "A", 4, (-2.0, 6.0, 0.0))
    add("CA", "PHE", "A", 4, (-1.5, 5.0, 0.8))
    add("C", "PHE", "A", 4, (-2.4, 4.0, 1.4))
    add("O", "PHE", "A", 4, (-3.6, 4.1, 1.2))
    add("CB", "PHE", "A", 4, (-0.6, 5.7, 1.8))
    phe_ring = ring((0.0, 8.0, 0.0), "z")
    for name, point in zip(
        ["CG", "CD1", "CE1", "CZ", "CE2", "CD2"], phe_ring, strict=False
    ):
        add(name, "PHE", "A", 4, point)

    # --- LEU 5: an apolar pair for the hydrophobic detector ----------------
    add("N", "LEU", "A", 5, (-6.0, 1.0, 4.0))
    add("CA", "LEU", "A", 5, (-5.0, 0.5, 4.5))
    add("C", "LEU", "A", 5, (-5.4, -0.6, 5.4))
    add("O", "LEU", "A", 5, (-6.6, -0.9, 5.5))
    add("CB", "LEU", "A", 5, (-4.2, 1.6, 5.2))
    add("CG", "LEU", "A", 5, (-3.2, 2.3, 4.3))
    add("CD1", "LEU", "A", 5, (-2.4, 3.4, 5.0))
    add("CD2", "LEU", "A", 5, (-2.3, 1.3, 3.6))

    # --- ARG 6: guanidinium centred on the PHE ring axis, 5.03 A below -----
    # A cation-pi interaction: zero lateral offset, well inside the 6 A cutoff.
    add("N", "ARG", "A", 6, (2.0, 11.0, -6.0))
    add("CA", "ARG", "A", 6, (1.5, 10.0, -5.2))
    add("C", "ARG", "A", 6, (2.4, 9.6, -4.1))
    add("O", "ARG", "A", 6, (3.5, 10.1, -3.9))
    add("CB", "ARG", "A", 6, (1.2, 9.0, -6.1))
    add("CG", "ARG", "A", 6, (0.6, 8.6, -5.5))
    add("CD", "ARG", "A", 6, (0.4, 8.2, -5.0))
    add("NE", "ARG", "A", 6, (1.2, 8.0, -5.2))
    add("CZ", "ARG", "A", 6, (0.0, 8.0, -4.5))
    add("NH1", "ARG", "A", 6, (-0.6, 8.8, -5.2))
    add("NH2", "ARG", "A", 6, (-0.6, 7.2, -5.2))

    # --- THR 7: OG1 accepts a halogen bond from the ligand chlorine --------
    # C7-CL1...OG1 is collinear, with CL...O at 3.30 A.
    add("N", "THR", "A", 7, (-10.5, 10.0, 5.0))
    add("CA", "THR", "A", 7, (-10.0, 9.4, 3.8))
    add("C", "THR", "A", 7, (-11.0, 8.5, 3.1))
    add("O", "THR", "A", 7, (-12.1, 8.9, 2.8))
    add("CB", "THR", "A", 7, (-9.5, 8.6, 4.4))
    add("OG1", "THR", "A", 7, (-9.0, 8.0, 3.80))
    add("CG2", "THR", "A", 7, (-8.8, 9.6, 5.2))

    # --- Ligand: benzene ring stacked 3.80 A above the PHE ring -----------
    lig_ring = ring((0.0, 8.0, 3.80), "z", start=math.pi / 6.0)
    for name, point in zip(
        ["C1", "C2", "C3", "C4", "C5", "C6"], lig_ring, strict=False
    ):
        add(name, "LIG", "B", 1, point, b=25.0, element="C")
    # Chlorine making a halogen bond to the LEU backbone O: C-Cl...O is linear.
    add("C7", "LIG", "B", 1, (-4.0, 8.0, 3.80), b=25.0, element="C")
    add("CL1", "LIG", "B", 1, (-5.7, 8.0, 3.80), b=25.0, element="CL")
    add("O1", "LIG", "B", 1, (2.0, 10.5, 3.80), b=25.0, element="O")

    # --- Metal centre, water and a free ion --------------------------------
    add("ZN", "ZN", "C", 1, (2.80, 0.0, 2.10), b=20.0, element="ZN")
    add("O", "HOH", "D", 1, (10.0, 10.0, 10.0), b=40.0, element="O")
    add("CL", "CL", "D", 2, (12.0, 12.0, 12.0), b=40.0, element="CL")

    return atoms


def plddt() -> list[Atom]:
    """Poly-alanine whose B-factors sweep every AlphaFold confidence band."""
    bands = [95.0, 92.0, 85.0, 75.0, 65.0, 55.0, 45.0, 30.0]
    atoms: list[Atom] = []
    serial = 1
    for index, value in enumerate(bands):
        res_id = index + 1
        x = index * 3.8  # roughly one residue of extended backbone
        for name, offset, element in (
            ("N", (0.0, 0.0, 0.0), "N"),
            ("CA", (1.2, 0.5, 0.0), "C"),
            ("C", (2.4, 0.0, 0.0), "C"),
            ("O", (2.5, -1.2, 0.0), "O"),
            ("CB", (1.3, 1.6, 1.0), "C"),
        ):
            atoms.append(
                Atom(
                    serial,
                    name,
                    "ALA",
                    "A",
                    res_id,
                    x + offset[0],
                    offset[1],
                    offset[2],
                    1.0,
                    value,
                    element,
                )
            )
            serial += 1
    return atoms


def geometry() -> list[Atom]:
    """Four atoms with an exactly known distance, angle and dihedral.

    C1-C2 is 1.500 A. C1-C2-C3 is exactly 90 degrees. The C1-C2-C3-C4 torsion
    is exactly -90 degrees under the IUPAC convention.
    """
    return [
        Atom(1, "C1", "GLY", "A", 1, 1.500, 0.000, 0.000, 1.0, 10.0, "C"),
        Atom(2, "C2", "GLY", "A", 1, 0.000, 0.000, 0.000, 1.0, 20.0, "C"),
        Atom(3, "C3", "GLY", "A", 1, 0.000, 1.500, 0.000, 1.0, 30.0, "C"),
        Atom(4, "C4", "GLY", "A", 1, 0.000, 1.500, 1.500, 1.0, 40.0, "C"),
    ]


def awkward() -> list[Atom]:
    """A chain carrying the complications real depositions carry.

    Each is something the PDB routinely contains and a synthetic fixture
    routinely does not, gathered into one small file so that a test can name
    the feature it is about:

    ``residues -1 and 0``
        an expression tag, numbered before the construct starts.
    ``ALA 1 in two conformations``
        alternate locations A and B at partial occupancy, so the residue has
        two atoms of each name and neither is the atom.
    ``a gap between 2 and 100``
        an unmodelled loop: consecutive in the file, ninety-seven apart in
        the numbering.
    ``TRP 100, GLY 100A, GLY 100B``
        insertion codes, as antibody numbering uses them — three residues
        that a reader keying on the number alone collapses into one.
    ``MSE 101``
        selenomethionine, which is a modified residue written as HETATM and
        is nonetheless protein as far as a cartoon is concerned.
    ``UNK 102``
        a residue whose identity was not determined.
    ``chain a``
        a lower-case chain beside chain ``A``. The selection language folds
        case, so these two are one chain to it and two to the file.
    ``CA in two senses``
        a calcium ion named ``CA`` in a residue named ``CA``, beside the
        C-alpha atoms named ``CA``. The element column is the only thing
        telling them apart.
    ``a zero-occupancy atom``
        modelled but not believed.
    ``an atom with no element column``
        legal, and common in older and generated files.
    ``formal charges``
        on the lysine nitrogen and the aspartate oxygen.
    ``a duplicated atom``
        the same name twice in one residue at identical coordinates, which is
        a deposition error rather than an alternate location.
    """
    atoms: list[Atom] = []
    serial = 1

    def add(name, res_name, chain, res_id, xyz, **extra):
        nonlocal serial
        atoms.append(
            Atom(
                serial,
                name,
                res_name,
                chain,
                res_id,
                xyz[0],
                xyz[1],
                xyz[2],
                extra.pop("occupancy", 1.0),
                extra.pop("b_factor", 20.0),
                extra.pop("element", name[0]),
                **extra,
            )
        )
        serial += 1

    # --- the expression tag, numbered below one -----------------------------
    add("N", "SER", "A", -1, (0.0, 0.0, 0.0), element="N")
    add("CA", "SER", "A", -1, (1.5, 0.0, 0.0))
    add("C", "SER", "A", -1, (2.0, 1.4, 0.0))
    add("N", "GLY", "A", 0, (3.3, 1.6, 0.0), element="N")
    add("CA", "GLY", "A", 0, (4.0, 2.9, 0.0))
    add("C", "GLY", "A", 0, (5.5, 2.8, 0.0))

    # --- ALA 1 in two conformations, 60:40 ----------------------------------
    for altloc, occupancy, offset in (("A", 0.6, 0.0), ("B", 0.4, 0.7)):
        add(
            "N",
            "ALA",
            "A",
            1,
            (6.2, 3.9, offset),
            element="N",
            altloc=altloc,
            occupancy=occupancy,
        )
        add("CA", "ALA", "A", 1, (7.6, 4.1, offset), altloc=altloc, occupancy=occupancy)
        add("CB", "ALA", "A", 1, (8.1, 5.5, offset), altloc=altloc, occupancy=occupancy)
        add(
            "C",
            "ALA",
            "A",
            1,
            (8.3, 3.2, offset + 1.0),
            altloc=altloc,
            occupancy=occupancy,
        )

    # --- LYS 2, carrying a formal charge and a zero-occupancy tip -----------
    add("N", "LYS", "A", 2, (9.6, 3.4, 0.0), element="N")
    add("CA", "LYS", "A", 2, (10.4, 2.3, 0.5))
    add("CB", "LYS", "A", 2, (11.8, 2.7, 0.9))
    add("CG", "LYS", "A", 2, (12.7, 1.5, 1.2))
    add("CD", "LYS", "A", 2, (14.1, 1.9, 1.6))
    add("CE", "LYS", "A", 2, (15.0, 0.7, 1.9))
    # Modelled, but with nothing behind it: occupancy zero.
    add("NZ", "LYS", "A", 2, (16.4, 1.1, 2.3), element="N", charge="1+", occupancy=0.0)

    # --- the gap, and then the insertion-coded run --------------------------
    add("N", "TRP", "A", 100, (20.0, 0.0, 0.0), element="N")
    add("CA", "TRP", "A", 100, (21.4, 0.2, 0.3))
    # The same residue number three times over, told apart only by column 27.
    add("N", "GLY", "A", 100, (22.1, 1.4, 0.6), element="N", ins_code="A")
    add("CA", "GLY", "A", 100, (23.5, 1.7, 0.9), ins_code="A")
    add("N", "GLY", "A", 100, (24.2, 2.9, 1.2), element="N", ins_code="B")
    add("CA", "GLY", "A", 100, (25.6, 3.2, 1.5), ins_code="B")

    # --- selenomethionine, and an unidentified residue ----------------------
    add("N", "MSE", "A", 101, (26.3, 4.4, 1.8), element="N", hetero=True)
    add("CA", "MSE", "A", 101, (27.7, 4.7, 2.1), hetero=True)
    add("CB", "MSE", "A", 101, (28.4, 5.9, 2.4), hetero=True)
    add("SE", "MSE", "A", 101, (29.9, 5.6, 3.2), element="SE", hetero=True)
    add("N", "UNK", "A", 102, (30.8, 6.8, 3.5), element="N")
    # No element column at all, which a reader has to derive from the name.
    add("CA", "UNK", "A", 102, (32.2, 7.1, 3.8), element="")

    # --- a lower-case chain beside the upper-case one -----------------------
    add("N", "VAL", "a", 1, (0.0, 20.0, 0.0), element="N")
    add("CA", "VAL", "a", 1, (1.4, 20.3, 0.3))
    # The same atom twice, at the same place: a deposition error, not an altloc.
    add("CB", "VAL", "a", 1, (2.1, 21.5, 0.6))
    add("CB", "VAL", "a", 1, (2.1, 21.5, 0.6))

    # --- calcium, in a file that also has C-alphas --------------------------
    add(
        "CA",
        "CA",
        "B",
        1,
        (10.0, 20.0, 10.0),
        element="CA",
        hetero=True,
        charge="2+",
        b_factor=35.0,
    )
    # --- a glycan, a sulfate and a water ------------------------------------
    add("C1", "NAG", "C", 1, (14.0, 20.0, 10.0), b_factor=40.0)
    add("O5", "NAG", "C", 1, (15.2, 20.6, 10.3), element="O", b_factor=40.0)
    add("S", "SO4", "C", 2, (18.0, 20.0, 10.0), element="S", b_factor=45.0)
    add(
        "O1", "SO4", "C", 2, (19.4, 20.3, 10.2), element="O", charge="1-", b_factor=45.0
    )
    add("O", "HOH", "D", 1, (12.0, 24.0, 12.0), element="O", b_factor=50.0)

    return atoms


def nucleic() -> list[Atom]:
    """A DNA dinucleotide and an RNA one, with the backbone names they use.

    The nucleic path is a whole half of the selection language — ``nucleic``,
    ``backbone``, ``sidechain`` and the base rings all take a different branch
    from the protein one — and nothing else under ``tests/data`` exercises it.
    The ribose ``O2'`` is what distinguishes the RNA strand from the DNA one.
    """
    atoms: list[Atom] = []
    serial = 1

    def add(name, res_name, chain, res_id, xyz, element=None):
        nonlocal serial
        atoms.append(
            Atom(
                serial,
                name,
                res_name,
                chain,
                res_id,
                xyz[0],
                xyz[1],
                xyz[2],
                1.0,
                25.0,
                element or ("P" if name == "P" else name[0]),
            )
        )
        serial += 1

    def nucleotide(res_name, chain, res_id, origin, ribose: bool):
        x, y, z = origin
        backbone = [
            ("P", (0.0, 0.0, 0.0), "P"),
            ("OP1", (0.6, 1.3, 0.2), "O"),
            ("OP2", (0.2, -0.8, 1.2), "O"),
            ("O5'", (1.0, -0.6, -1.0), "O"),
            ("C5'", (2.4, -0.4, -0.9), "C"),
            ("C4'", (3.0, -1.0, 0.3), "C"),
            ("O4'", (2.6, -0.3, 1.5), "O"),
            ("C3'", (4.5, -1.0, 0.4), "C"),
            ("O3'", (5.1, -1.9, 1.3), "O"),
            ("C2'", (4.9, 0.4, 0.8), "C"),
            ("C1'", (3.6, 1.1, 1.3), "C"),
        ]
        if ribose:
            backbone.append(("O2'", (5.9, 0.5, 1.8), "O"))
        for name, (dx, dy, dz), element in backbone:
            add(name, res_name, chain, res_id, (x + dx, y + dy, z + dz), element)
        # A six-membered base ring, offset from the sugar.
        for index, point in enumerate(ring((x + 3.2, y + 3.4, z + 1.5), "z")):
            name = ["N1", "C2", "N3", "C4", "C5", "C6"][index]
            add(name, res_name, chain, res_id, point, name[0])

    nucleotide("DA", "A", 1, (0.0, 0.0, 0.0), ribose=False)
    nucleotide("DT", "A", 2, (0.0, 0.0, 6.8), ribose=False)
    nucleotide("G", "B", 1, (20.0, 0.0, 0.0), ribose=True)
    nucleotide("U", "B", 2, (20.0, 0.0, 6.8), ribose=True)
    return atoms


#: The mmCIF columns written, in order. `label_*` and `auth_*` deliberately
#: disagree: the label chain is a multi-character identifier the PDB format
#: has no column for, and the label sequence numbering is the contiguous one
#: mmCIF requires, so a selection written against one is wrong against the
#: other. That divergence is the point of having a CIF fixture at all.
_CIF_COLUMNS = (
    "group_PDB",
    "id",
    "type_symbol",
    "label_atom_id",
    "label_alt_id",
    "label_comp_id",
    "label_asym_id",
    "label_seq_id",
    "pdbx_PDB_ins_code",
    "Cartn_x",
    "Cartn_y",
    "Cartn_z",
    "occupancy",
    "B_iso_or_equiv",
    "pdbx_formal_charge",
    "auth_seq_id",
    "auth_comp_id",
    "auth_asym_id",
    "auth_atom_id",
    "pdbx_PDB_model_num",
)


def _cif_charge(charge: str) -> str:
    """Convert a PDB formal charge to the mmCIF spelling.

    The PDB writes the sign last (``1+``, ``2-``); mmCIF writes a plain signed
    integer. A reader given the PDB spelling in a CIF file fails on the whole
    file, not on the one atom.
    """
    if not charge:
        return ""
    if charge.endswith(("+", "-")):
        sign = "-" if charge.endswith("-") else ""
        return f"{sign}{charge[:-1]}"
    return charge


def _cif_value(value: str) -> str:
    """Quote a CIF value if it needs it. An unset one is a bare ``?``."""
    if value == "":
        return "?"
    if "'" in value:  # ribose atom names: O5', C1'
        return f'"{value}"'
    if " " in value:
        return f"'{value}'"
    return value


def write_cif(path: str, atoms: list[Atom], name: str = "awkward") -> None:
    """Write the same atoms as mmCIF, with label and auth identifiers apart."""
    # One contiguous label_seq_id per chain, which is what mmCIF means by it,
    # against the author numbering the PDB file carries.
    label_seq: dict[tuple[str, int, str], int] = {}
    for atom in atoms:
        key = (atom.chain, atom.res_id, atom.ins_code)
        if key not in label_seq:
            label_seq[key] = len(label_seq) + 1

    rows = []
    for atom in atoms:
        rows.append(
            [
                "HETATM" if line(atom).startswith("HETATM") else "ATOM",
                str(atom.serial),
                atom.element or "?",
                atom.name,
                atom.altloc,
                atom.res_name,
                f"{atom.chain}{atom.chain}{atom.chain}",  # multi-character
                str(label_seq[(atom.chain, atom.res_id, atom.ins_code)]),
                atom.ins_code,
                f"{atom.x:.3f}",
                f"{atom.y:.3f}",
                f"{atom.z:.3f}",
                f"{atom.occupancy:.2f}",
                f"{atom.b_factor:.2f}",
                _cif_charge(atom.charge),
                str(atom.res_id),
                atom.res_name,
                atom.chain,
                atom.name,
                "1",
            ]
        )

    with open(path, "w", encoding="utf-8") as handle:
        handle.write(f"data_{name}\n#\n")
        handle.write("# Synthetic fixture generated by tests/data/make_fixtures.py\n")
        handle.write("loop_\n")
        for column in _CIF_COLUMNS:
            handle.write(f"_atom_site.{column}\n")
        for row in rows:
            handle.write(" ".join(_cif_value(value) for value in row) + "\n")
        handle.write("#\n")
    print(f"wrote {path} ({len(atoms)} atoms, mmCIF)")


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    write(os.path.join(here, "site.pdb"), site())
    write(os.path.join(here, "plddt.pdb"), plddt())
    write(os.path.join(here, "geometry.pdb"), geometry())
    write(os.path.join(here, "awkward.pdb"), awkward())
    write_cif(os.path.join(here, "awkward.cif"), awkward())
    write(os.path.join(here, "nucleic.pdb"), nucleic())
    write(os.path.join(here, "ensemble.pdb"), plddt(), models=3)
