"""Generate the test structures under ``tests/data``.

The fixtures are synthetic and built from exact coordinates so that tests can
assert real numbers — a 2.80 A hydrogen bond is 2.80 A because it was placed
there, not because a real structure happened to have one. Run with any Python
that has no dependencies beyond the standard library::

    python tests/data/make_fixtures.py

Committed output:

``site.pdb``
    A synthetic binding site exercising every interaction detector: a hydrogen
    bond with an explicit hydrogen, a salt bridge, an aromatic stack, a
    cation-pi, a halogen bond, a metal centre, a hydrophobic pair, plus a
    water and a monoatomic ion.
``plddt.pdb``
    A poly-alanine chain whose B-factors sweep the four AlphaFold confidence
    bands.
``geometry.pdb``
    Four atoms at coordinates with an exactly known distance, angle and
    dihedral.
"""

from __future__ import annotations

import math
import os

Atom = tuple[int, str, str, str, int, float, float, float, float, float, str]

HEADER = "REMARK   Synthetic fixture generated by tests/data/make_fixtures.py\n"


def line(atom: Atom) -> str:
    serial, name, res_name, chain, res_id, x, y, z, occupancy, b, element = atom
    record = "HETATM" if res_name in ("LIG", "HOH", "ZN", "CL") else "ATOM  "
    padded = f" {name:<3}" if len(name) < 4 else name
    return (
        f"{record}{serial:5d} {padded}{res_name:>4}{chain:>2}{res_id:4d}    "
        f"{x:8.3f}{y:8.3f}{z:8.3f}{occupancy:6.2f}{b:6.2f}"
        f"{'':>10}{element:>2}\n"
    )


def write(path: str, atoms: list[Atom]) -> None:
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(HEADER)
        for atom in atoms:
            handle.write(line(atom))
        handle.write("END\n")
    print(f"wrote {path} ({len(atoms)} atoms)")


def ring(centre, normal_axis: str, radius: float = 1.39, start: float = 0.0):
    """Regular hexagon of ring atoms in a plane normal to ``normal_axis``."""
    cx, cy, cz = centre
    points = []
    for i in range(6):
        angle = start + i * math.pi / 3.0
        dx, dy = radius * math.cos(angle), radius * math.sin(angle)
        if normal_axis == "z":
            points.append((cx + dx, cy + dy, cz))
        elif normal_axis == "y":
            points.append((cx + dx, cy, cz + dy))
        else:
            points.append((cx, cy + dx, cz + dy))
    return points


def site() -> list[Atom]:
    atoms: list[Atom] = []
    serial = 1

    def add(name, res_name, chain, res_id, xyz, b=30.0, element=None, occupancy=1.0):
        nonlocal serial
        element = element or name[0]
        atoms.append(
            (
                serial,
                name,
                res_name,
                chain,
                res_id,
                xyz[0],
                xyz[1],
                xyz[2],
                occupancy,
                b,
                element,
            )
        )
        serial += 1

    # --- SER 1: donates a hydrogen bond to ASP 2 OD1 -----------------------
    # OG at (0,0,0); HG points at OD1 so the D-H...A angle is exactly 180.
    add("N", "SER", "A", 1, (-2.5, 1.2, 0.0))
    add("CA", "SER", "A", 1, (-1.5, 0.2, 0.0))
    add("C", "SER", "A", 1, (-2.0, -1.2, 0.0))
    add("O", "SER", "A", 1, (-3.2, -1.5, 0.0))
    add("CB", "SER", "A", 1, (-0.7, 0.5, 1.2))
    add("OG", "SER", "A", 1, (0.0, 0.0, 0.0))
    add("HG", "SER", "A", 1, (0.98, 0.0, 0.0), element="H")

    # --- ASP 2: acceptor at exactly 2.80 A from SER OG --------------------
    add("N", "ASP", "A", 2, (5.0, 3.0, 0.0))
    add("CA", "ASP", "A", 2, (4.5, 1.8, 0.0))
    add("C", "ASP", "A", 2, (5.5, 0.8, 0.6))
    add("O", "ASP", "A", 2, (6.6, 1.2, 1.0))
    add("CB", "ASP", "A", 2, (4.0, -0.3, -0.9))
    add("CG", "ASP", "A", 2, (3.5, -0.6, 0.4))
    add("OD1", "ASP", "A", 2, (2.80, 0.0, 0.0))
    add("OD2", "ASP", "A", 2, (3.9, -1.6, 1.0))

    # --- LYS 3: salt bridge to ASP 2, and cation-pi over the ligand ring ---
    add("N", "LYS", "A", 3, (7.0, -3.0, 0.0))
    add("CA", "LYS", "A", 3, (6.5, -2.0, 0.9))
    add("C", "LYS", "A", 3, (7.5, -1.0, 1.4))
    add("O", "LYS", "A", 3, (8.6, -1.3, 1.8))
    add("CB", "LYS", "A", 3, (5.5, -1.3, 0.1))
    add("CG", "LYS", "A", 3, (4.8, -2.2, -0.9))
    add("CD", "LYS", "A", 3, (4.0, -3.2, -0.2))
    add("CE", "LYS", "A", 3, (3.4, -4.0, -1.3))
    # NZ 4.30 A from the carboxylate centroid (2.90, -0.80, 0.50): a salt bridge.
    add("NZ", "LYS", "A", 3, (2.90, -5.10, 0.50))

    # --- PHE 4: aromatic ring in the z = 0 plane, centred at (0, 8, 0) -----
    add("N", "PHE", "A", 4, (-2.0, 6.0, 0.0))
    add("CA", "PHE", "A", 4, (-1.5, 5.0, 0.8))
    add("C", "PHE", "A", 4, (-2.4, 4.0, 1.4))
    add("O", "PHE", "A", 4, (-3.6, 4.1, 1.2))
    add("CB", "PHE", "A", 4, (-0.6, 5.7, 1.8))
    phe_ring = ring((0.0, 8.0, 0.0), "z")
    for name, point in zip(
        ["CG", "CD1", "CE1", "CZ", "CE2", "CD2"], phe_ring, strict=False
    ):
        add(name, "PHE", "A", 4, point)

    # --- LEU 5: an apolar pair for the hydrophobic detector ----------------
    add("N", "LEU", "A", 5, (-6.0, 1.0, 4.0))
    add("CA", "LEU", "A", 5, (-5.0, 0.5, 4.5))
    add("C", "LEU", "A", 5, (-5.4, -0.6, 5.4))
    add("O", "LEU", "A", 5, (-6.6, -0.9, 5.5))
    add("CB", "LEU", "A", 5, (-4.2, 1.6, 5.2))
    add("CG", "LEU", "A", 5, (-3.2, 2.3, 4.3))
    add("CD1", "LEU", "A", 5, (-2.4, 3.4, 5.0))
    add("CD2", "LEU", "A", 5, (-2.3, 1.3, 3.6))

    # --- ARG 6: guanidinium centred on the PHE ring axis, 5.03 A below -----
    # A cation-pi interaction: zero lateral offset, well inside the 6 A cutoff.
    add("N", "ARG", "A", 6, (2.0, 11.0, -6.0))
    add("CA", "ARG", "A", 6, (1.5, 10.0, -5.2))
    add("C", "ARG", "A", 6, (2.4, 9.6, -4.1))
    add("O", "ARG", "A", 6, (3.5, 10.1, -3.9))
    add("CB", "ARG", "A", 6, (1.2, 9.0, -6.1))
    add("CG", "ARG", "A", 6, (0.6, 8.6, -5.5))
    add("CD", "ARG", "A", 6, (0.4, 8.2, -5.0))
    add("NE", "ARG", "A", 6, (1.2, 8.0, -5.2))
    add("CZ", "ARG", "A", 6, (0.0, 8.0, -4.5))
    add("NH1", "ARG", "A", 6, (-0.6, 8.8, -5.2))
    add("NH2", "ARG", "A", 6, (-0.6, 7.2, -5.2))

    # --- THR 7: OG1 accepts a halogen bond from the ligand chlorine --------
    # C7-CL1...OG1 is collinear, with CL...O at 3.30 A.
    add("N", "THR", "A", 7, (-10.5, 10.0, 5.0))
    add("CA", "THR", "A", 7, (-10.0, 9.4, 3.8))
    add("C", "THR", "A", 7, (-11.0, 8.5, 3.1))
    add("O", "THR", "A", 7, (-12.1, 8.9, 2.8))
    add("CB", "THR", "A", 7, (-9.5, 8.6, 4.4))
    add("OG1", "THR", "A", 7, (-9.0, 8.0, 3.80))
    add("CG2", "THR", "A", 7, (-8.8, 9.6, 5.2))

    # --- Ligand: benzene ring stacked 3.80 A above the PHE ring -----------
    lig_ring = ring((0.0, 8.0, 3.80), "z", start=math.pi / 6.0)
    for name, point in zip(
        ["C1", "C2", "C3", "C4", "C5", "C6"], lig_ring, strict=False
    ):
        add(name, "LIG", "B", 1, point, b=25.0, element="C")
    # Chlorine making a halogen bond to the LEU backbone O: C-Cl...O is linear.
    add("C7", "LIG", "B", 1, (-4.0, 8.0, 3.80), b=25.0, element="C")
    add("CL1", "LIG", "B", 1, (-5.7, 8.0, 3.80), b=25.0, element="CL")
    add("O1", "LIG", "B", 1, (2.0, 10.5, 3.80), b=25.0, element="O")

    # --- Metal centre, water and a free ion --------------------------------
    add("ZN", "ZN", "C", 1, (2.80, 0.0, 2.10), b=20.0, element="ZN")
    add("O", "HOH", "D", 1, (10.0, 10.0, 10.0), b=40.0, element="O")
    add("CL", "CL", "D", 2, (12.0, 12.0, 12.0), b=40.0, element="CL")

    return atoms


def plddt() -> list[Atom]:
    """Poly-alanine whose B-factors sweep every AlphaFold confidence band."""
    bands = [95.0, 92.0, 85.0, 75.0, 65.0, 55.0, 45.0, 30.0]
    atoms: list[Atom] = []
    serial = 1
    for index, value in enumerate(bands):
        res_id = index + 1
        x = index * 3.8  # roughly one residue of extended backbone
        for name, offset, element in (
            ("N", (0.0, 0.0, 0.0), "N"),
            ("CA", (1.2, 0.5, 0.0), "C"),
            ("C", (2.4, 0.0, 0.0), "C"),
            ("O", (2.5, -1.2, 0.0), "O"),
            ("CB", (1.3, 1.6, 1.0), "C"),
        ):
            atoms.append(
                (
                    serial,
                    name,
                    "ALA",
                    "A",
                    res_id,
                    x + offset[0],
                    offset[1],
                    offset[2],
                    1.0,
                    value,
                    element,
                )
            )
            serial += 1
    return atoms


def geometry() -> list[Atom]:
    """Four atoms with an exactly known distance, angle and dihedral.

    C1-C2 is 1.500 A. C1-C2-C3 is exactly 90 degrees. The C1-C2-C3-C4 torsion
    is exactly -90 degrees under the IUPAC convention.
    """
    return [
        (1, "C1", "GLY", "A", 1, 1.500, 0.000, 0.000, 1.0, 10.0, "C"),
        (2, "C2", "GLY", "A", 1, 0.000, 0.000, 0.000, 1.0, 20.0, "C"),
        (3, "C3", "GLY", "A", 1, 0.000, 1.500, 0.000, 1.0, 30.0, "C"),
        (4, "C4", "GLY", "A", 1, 0.000, 1.500, 1.500, 1.0, 40.0, "C"),
    ]


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    write(os.path.join(here, "site.pdb"), site())
    write(os.path.join(here, "plddt.pdb"), plddt())
    write(os.path.join(here, "geometry.pdb"), geometry())
